# Generated by Django 4.1.3 on 2023-02-25 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='target',
            field=models.CharField(help_text='打开方式', max_length=30, verbose_name='打开方式'),
        ),
    ]
