# Generated by Django 4.1.3 on 2023-02-25 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_menu_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='hide',
            field=models.IntegerField(choices=[(0, '可见'), (1, '不可见')], default=1, help_text='是否可见：0-可见 1-不可见', verbose_name='是否可见：0-可见 1-不可见'),
        ),
    ]
